### ISSUE TITLE
OSError: 23 after multiple invocations of `query_once()` in a row

### ISSUE THREAD

**Issue by mirko** [cbrand/micropython-mdns#27] opened 2024-11-17 21:35 UTC
When calling:
```
mdns_client = MDNSClient(self.sta.ifconfig()[0])
sd = TXTServiceDiscovery(self.mdns_client)
await sd.query_once(service, protocol, timeout=1)
mdns_client.stop()
```

a couple of times in a row (usually not more than 10), sooner or later an asyncio task will throw an `OSError: 23`-exception (at least on ESP32).

Stack trace gathered and printed via asyncio global exception handler:
```
Traceback (most recent call last):
  File "asyncio/core.py", line 1, in run
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in call_exception_handler
  File "/TMP/pvtool/main.py", line 127, in async_crash_hdlr
  File "asyncio/core.py", line 1, in run_until_complete
  File "/TMP/mdns_client/client.py", line 74, in start
  File "/TMP/mdns_client/client.py", line 80, in _init_socket
  File "/TMP/mdns_client/client.py", line 65, in _make_socket
OSError: 23
```

This is a problematic on several levels:
a) The exception is thrown in a task and there's not "the single spot" where to catch and ignore / handle it
b) Even if quick&dirty silencing the exception, once it occurs, we don't recover from the situation but keep running into OSError 23

While from reading the code it looks sockets are closed correctly and even the `socket.SO_REUSEADDR`-flag is used, it appears we're reaching a(n open socket-)limit.

Sligtly related to: https://github.com/cbrand/micropython-mdns/issues/25 as we use `query_once()` and `stop()` the listener right after.

**Comment by cbrand** [comment] 2024-11-18 10:52
Hey. 

Does it also happen if you do not stop the underlying socket?
I guess the issue might arise from the socket being closed and opened in succession as this is not really something which the ESP is made for.

Also in the other ticket https://github.com/cbrand/micropython-mdns/issues/25 you said that the query is ran once and not multiple times. In the described scenario here I would recommend not closing the socket in between if feasible.

**Comment by cbrand** [comment] 2024-11-18 15:05
Yeah absolutely.
I am also quite sure that the issue is sadly somewhere down the chain but I think I did not get my question over correctly:

So to double check the issue does not happen if you execute it without the `stop` method.
E.g. this does not trigger the error?

```python
import asyncio
from mdns_client.service_discovery.txt_discovery import TXTServiceDiscovery
from mdns_client import Client as MDNSClient

sta = network.WLAN(network.STA_IF)
#sta.connect(essid, passwd)

async def dns_sd():
    mdns_client = MDNSClient(sta.ifconfig()[0])
    sd = TXTServiceDiscovery(mdns_client)
    return await sd.query_once("_http", "_tcp", timeout=1)

async def mainloop():
    while True:
        print(await dns_sd())
        await asyncio.sleep(1)

asyncio.run(mainloop())
```

If that is the case it is totally fine to call query once multiple times. The stop and restart of the socket might be a problem.

**Comment by cbrand** [comment] 2024-11-18 15:06
If so. Could you also tell me the micropython version you are using?

**Comment by mirko** [comment] 2024-11-18 15:06
Thanks for your effort, I just in the same second commented with a finding of my example code being wrong.
Will test further and report back, but most likely I just screwed up.

**Comment by mirko** [comment] 2024-12-06 21:27
The issue actually *does* exist. I covered it up by already modified mdns-source.
But with master/HEAD the above code reliably triggers the issue on ESP32 for me.

**Comment by mirko** [comment] 2024-12-06 21:37
And so far - as expected - I can not reproduce it with `ONLY_ONCE = False`

**Comment by mirko** [comment] 2024-12-06 22:57
For what it's worth: I can#t reproduce that error by just creating sockets:
```
import network
import socket
import time

def dotted_ip_to_bytes(ip: str) -> bytes:
    """
    Convert a dotted IPv4 address string into four bytes, with
    some sanity checks
    """
    ip_ints = [int(i) for i in ip.split(".")]
    if len(ip_ints) != 4 or any(i < 0 or i > 255 for i in ip_ints):
        raise ValueError
    return bytes(ip_ints)

wlan = network.WLAN(network.STA_IF)
local_ip = wlan.ifconfig()[0]

sockets = []

i = 0
while True:
    i+=1
    print("Round:", i)
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    member_info = dotted_ip_to_bytes("224.0.0.251") + dotted_ip_to_bytes(local_ip)
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, member_info)
    sock.setblocking(False)
    #sockets.append(sock)
    time.sleep(1)
```

whereas, if I explicitly keep created sockets (e.g. adding them to a global array), I run into the same issue (`OSError: 23`).

**Comment by mirko** [comment] 2024-12-13 18:26
What I missed before but am seeing now - when only *actually* querying once and then continue with the asyncio loop, at some point I see the following for the two previously discovered devices:
```
MDNS Discovery: Service shellyem3-AAAAAAAAAAAA._http._tcp.local will be refreshed via MDNS with expiry at 3259338 ticks and TTL 120 (Current: 3201696 ticks)
MDNS Discovery: Service shellyem3-BBBBBBBBBBBB._http._tcp.local will be refreshed via MDNS with expiry at 3259059 ticks and TTL 120 (Current: 3201696 ticks)
```

**Comment by cbrand** [comment] 2024-12-15 11:57
> What I missed before but am seeing now - when only _actually_ querying once and then continue with the asyncio loop, at some point I see the following for the two previously discovered devices:
> 
> ```
> MDNS Discovery: Service shellyem3-AAAAAAAAAAAA._http._tcp.local will be refreshed via MDNS with expiry at 3259338 ticks and TTL 120 (Current: 3201696 ticks)
> MDNS Discovery: Service shellyem3-BBBBBBBBBBBB._http._tcp.local will be refreshed via MDNS with expiry at 3259059 ticks and TTL 120 (Current: 3201696 ticks)
> ```
> 
> which to me appears ike not all tasks where stopped - and sockets not closed.

Thanks! That was really helpful.
I think I know see what the root cause is thanks to this error.

The service discovery starts a loop too which does scan for expired data and it does not check on the underyling client if it is closed or not.
That at least explains the message being started and should be fixed in https://github.com/cbrand/micropython-mdns/commit/5bf8419e1b0b5fa59da48198f8b20b6624477520

As it also starts the client again before this change it might also fix the main issue in this ticket. I am compiling a new version and do a release. If you can check if that fixes it on your end it would be great.

**Comment by cbrand** [comment] 2024-12-15 13:47
The release with the potential fix is: https://github.com/cbrand/micropython-mdns/releases/tag/1.5.1

**Comment by mirko** [comment] 2024-12-15 17:22
Appears to be fixed indeed - see https://github.com/cbrand/micropython-mdns/issues/25#issuecomment-2543936736

Many thanks!

**Closed** 2024-12-15 17:44 UTC
