### ISSUE TITLE
OSError: -202 

### ISSUE THREAD

**Issue by jgomez109** [cbrand/micropython-mdns#2] opened 2021-06-15 01:10 UTC
I installed your firmware v1.15 and also  the official Micropython firmware for ESP32 v1.14 (then I run import upip
upip.install("micropython-mdns") but in both cases i got the same error:

**Traceback (most recent call last):
  File "<stdin>", line 35, in <module>
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "uasyncio/core.py", line 1, in run_until_complete
  File "/lib/mdns_client/client.py", line 182, in getaddrinfo
  File "/lib/mdns_client/client.py", line 195, in mdns_getaddr
OSError: -202**

CODE:

```
import network
import uasyncio
from mdns_client import Client
from machine import freq
freq(240000000)

ssid="MySsiD"
password="MyPassword"

wlan = network.WLAN(network.STA_IF)
wlan.active(True)

print("Intendando conectar a la red:", ssid)
wlan.connect(ssid, password)
while wlan.isconnected() == False:
    pass

ip, mask, gate, dns = wlan.ifconfig()
print("Conexion exitosa a la red", ssid)
print("Ip optenida:", ip)
print("Mascara de subred:", mask)
print("Puerta de enlace:", gate)
print("DNS:", dns)
print("\n")
gc.collect()


loop = uasyncio.get_event_loop()
client = Client(wlan.ifconfig()[0])

print(loop.run_until_complete(client.getaddrinfo("the-other-device.local", 80)))
```

**Comment by cbrand** [comment] 2021-06-15 13:37
Hey @jgomez109 

Did you fix it and can share what the issue was?

**Comment by jgomez109** [comment] 2021-06-15 16:09
> Hey @jgomez109
> 
> Did you fix it and can share what the issue was?

Hi. Sorry, by mistake I closed the issue. I still have it.

**Comment by cbrand** [comment] 2021-06-15 16:40
Hey @jgomez109 

So checking the source code the issue is that the specific device is not found on your network. The error message gets thrown to be compatible with the `getaddrinfo` on the ESP32.

See the code here: https://github.com/cbrand/micropython-mdns/blob/main/src/mdns_client/client.py#L195

If I try with the code to detect a local device on my network it seems to work as expected.

**Comment by jgomez109** [comment] 2021-06-15 20:34
> Hey @jgomez109
> 
> So checking the source code the issue is that the specific device is not found on your network. The error message gets thrown to be compatible with the `getaddrinfo` on the ESP32.
> 
> See the code here: https://github.com/cbrand/micropython-mdns/blob/main/src/mdns_client/client.py#L195
> 
> If I try with the code to detect a local device on my network it seems to work as expected.

It so rare because I have connected my device to the network  before (with the same code) and I used my device to serving a webpage to local users (Accessing by device IP). So now I wanted to serve the page through mDNS but I can not understand how is not found the device  on my network. Can you give me some advice or hint to solve it?

**Comment by cbrand** [comment] 2021-06-16 08:52
Hm without knowing how your network exactly looks like it is kind of hard to give any kind of advice here.

Normally why things don't work is that you either have the devices in different network segments which makes mdns not work as it doesn't work over network boundaries or that a firewall blocks it.

What you can do to verify if this works is to check if you can resolve on a laptop in the same network the MDNS address. On Linux this should resolve mdns calls to if you do `ping`.

As a longer aside: 
If you only want to use mdns for discovering another device in the network I would strongly advise you to not use the library here. MicroPython has itself MDNS included by now which is why I need to publish an own firmware for micropython in the first place to disable it and have access to the UDP Port for MDNS traffic.

So if you're only interested in resolving on your ESP mdns addresses use [`usocket.getaddrinfo`](https://docs.micropython.org/en/latest/library/usocket.html#socket-address-format-s) instead. If the domain is postfixed with `.local` it will do the MDNS query. For this you require to patch the "normal" MicroPython version on your ESP as the firmware which I publish has this feature disabled.

I guarantee that the embedded variant is much faster and more robust than the one in this library. You should only use this library if you require Service Discovery or Service Announcement in your MicroPython project.

**Comment by jgomez109** [comment] 2021-06-16 12:24
Thank you so much for your answer. God willing, If I can fix it, I'll tell you. Blessings!

**Comment by cbrand** [comment] 2021-06-16 12:25
You are welcome. Good luck!

**Closed by cbrand** 2021-06-16 12:25 UTC
